### ISSUE TITLE
Add a split timer and some kinda import/exporting for that data

### ISSUE THREAD

**Issue by IndianBoy42** [nc108x/2023-scoreboard#1]

**Comment by nc108x** [comment]
Have added a (albeit somewhat crude) log that shows a list of actions taken and the corresponding time.

Import/export is on the todo list but will probably be pushed back until we decide what data we actually want and figure out how we want to process the data (considering just generating lines of csv to copy paste to an excel file?)

**Comment by nc108x** [comment]
Took ages but have finally added a barebones export option to the scoreboard. 

It's just generating a string and copy/pasting it to an excel spreadsheet but hey if it works it works (σﾟ∀ﾟ)σ

Will leave it be unless we need more processing I feel like this should be enough for our purposes for now.
