### ISSUE TITLE
Make timer not epileptic/shaky

### ISSUE THREAD

**Issue by TrebledJ** [nc108x/2023-scoreboard#2]
Maybe try a monospaced font. I recommend ~~Monaco~~Courier New. 😃

**Comment by nc108x** [comment]
Updated to use Roboto Mono for now, timer should not shake anymore

**Comment by TrebledJ** [comment]
Great! Now I can rest in peace without conjuring schizophrenic nightmares of haunted text! ❤️ 

P.S. I still think ~~Monaco~~Courier New looks nicer.
